---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ keystone_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - keystone
      - keystone_ssh
  register: container_facts

- name: Checking free port for Keystone Admin
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ keystone_admin_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['keystone'] is not defined
    - inventory_hostname in groups['keystone']

- name: Checking free port for Keystone Public
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ keystone_public_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['keystone'] is not defined
    - inventory_hostname in groups['keystone']

- name: Checking free port for Keystone SSH
  vars:
    keystone_ssh: "{{ keystone_services['keystone-ssh'] }}"
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ keystone_ssh_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['keystone_ssh'] is not defined
    - keystone_ssh.enabled | bool
    - inventory_hostname in groups['keystone']

- name: Checking fernet_token_expiry in globals.yml. Update fernet_token_expiry to allowed value if this task fails
  run_once: true
  command:
    cmd: awk '/^fernet_token_expiry/ { print $2 }' "{{ node_config }}/globals.yml"
  delegate_to: localhost
  register: result
  changed_when: false
  failed_when:
    - result.stdout | regex_replace('(60|120|180|240|300|360|600|720|900|1200|1800|3600|7200|10800|14400|21600|28800|43200|86400|604800)', '') is search(".+")
