---
- name: Creating admin openrc file on the deploy node
  hosts: localhost
  become: true
  tasks:
    - name: Template out admin-openrc.sh
      template:
        src: "roles/common/templates/admin-openrc.sh.j2"
        dest: "{{ node_config }}/admin-openrc.sh"
        mode: 0644
      run_once: True
