---
- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
    check:
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-centos8-source
        - kolla-ansible-debian-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-ubuntu-source-multinode-ipv6
        - kolla-ansible-bifrost-centos-source
        # FIXME(mgoddard): Bifrost CentOS 8 support in progress.
        # - kolla-ansible-centos8-source-bifrost
        - kolla-ansible-centos-source-zun
        - kolla-ansible-centos8-source-zun
        - kolla-ansible-ubuntu-source-zun
        - kolla-ansible-centos-source-swift
        - kolla-ansible-centos8-source-swift
        - kolla-ansible-ubuntu-source-swift
        - kolla-ansible-centos-source-scenario-nfv
        - kolla-ansible-centos8-source-scenario-nfv
        - kolla-ansible-ubuntu-source-masakari
        - kolla-ansible-centos-source-masakari
        # FIXME(mgoddard): Masakari CentOS 8 job.
        # - kolla-ansible-centos8-source-masakari
        - kolla-ansible-centos-source-ironic
        - kolla-ansible-centos8-source-ironic
        - kolla-ansible-centos-binary-ironic
        - kolla-ansible-centos8-binary-ironic
        - kolla-ansible-ubuntu-source-ironic
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
        - kolla-ansible-centos-binary
        - kolla-ansible-centos8-binary
        - kolla-ansible-ubuntu-binary
        - kolla-ansible-centos-source-cells
        - kolla-ansible-centos8-source-cells
        - kolla-ansible-centos-source-mariadb
        - kolla-ansible-centos8-source-mariadb
        - kolla-ansible-ubuntu-source-mariadb
        - kolla-ansible-centos-source-ceph-ansible
        - kolla-ansible-centos8-source-ceph-ansible
        - kolla-ansible-ubuntu-source-ceph-ansible
        - kolla-ansible-centos-source-upgrade-ceph-ansible
        - kolla-ansible-ubuntu-source-upgrade-ceph-ansible
        - kolla-ansible-centos-source-linuxbridge
        - kolla-ansible-ubuntu-source-linuxbridge
    check-arm64:
      jobs:
        - kolla-ansible-debian-source-aarch64
    gate:
      queue: kolla
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-centos8-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
    periodic:
      jobs:
        - kolla-ansible-bifrost-centos-source
        - kolla-ansible-centos-source-zun
        - kolla-ansible-ubuntu-source-zun
        - kolla-ansible-ubuntu-source-masakari
        - kolla-ansible-centos-source-masakari
        - kolla-ansible-centos-source-scenario-nfv
        - kolla-ansible-centos-source-ironic
        - kolla-ansible-centos-binary-ironic
        - kolla-ansible-ubuntu-source-ironic
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
        - kolla-ansible-centos-source-mariadb
        - kolla-ansible-ubuntu-source-mariadb
